name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Deno

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Latest Version of Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Deno Format
        run: deno fmt --check

      - name: Deno Lint
        run: deno lint

      - name: Deno Test
        run: deno test
