name: Publish to JSR and NPM

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Publish package to JSR
        run: |
          deno run -A ./scripts/prep-jsr.ts ${{ github.ref }}
          deno publish --allow-dirty

      - name: build npm package
        run: deno run -A ./scripts/build_npm.ts ${{ github.ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: publish npm package
        run: |
          cd npm
          npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
